import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Script from "next/script";
import Header from "../components/Header.js";
import Footer from "../components/Footer.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "POC",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script src="https://kit.fontawesome.com/c18e4a61e7.js" crossOrigin="anonymous" />
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        <Script src="/netlifycode.js" />
      </body>
    </html>
  );
}
