import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Header from "../components/Header.js";
import Footer from "../components/Footer.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "POC",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossOrigin="anonymous" />
        <Script src="https://kit.fontawesome.com/c18e4a61e7.js" crossOrigin="anonymous" />
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        <Script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossOrigin="anonymous" />
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossOrigin="anonymous" />
        <Script src="/netlifycode.js" />
      </body>
    </html>
  );
}
