backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
          - label: "Images"
            name: "images"
            widget: list
            fields:
              - { label: "Image Path", name: "imagepath", widget: "string" }
          - label: "Home Cards"
            name: "homeCards"
            widget: "list"
            fields:
              - { label: "Card Number", name: "cardNumber", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
      - label: "Blog"
        name: "blog"
        file: "content/blog.md"
        fields:
          - label: "Blog Posts"
            name: "blogPosts"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - { label: "Post", name: "post", widget: "markdown" }
              - { label: "Publish Date", name: "date", widget: "datetime", date_format: "MM/DD/YYYY" }
